services:
  price-pusher:
    # build:
    #   context: .
    # Uncomment this line (and comment out the above lines) to use a prebuilt image. Replace <version>
    # with the latest released image of the EVM price pusher from this repo release page:
    # https://github.com/pyth-network/pyth-js/releases
    image: public.ecr.aws/pyth-network/xc-evm-price-pusher:v2.0.1
    restart: always
    env_file:
      - ./.env
    command:
      - "--"
      - "evm"
      # # you can choose to provide all the options here or a path to the config file
      # # we are providing a path to the config file
      # - "--config"
      # - "/command_config"
      - "--evm-endpoint"
      # Replace this with RPC endpoint URL for the EVM network.
      - "https://zksync2-testnet.zksync.dev"
      - "--mnemonic-file"
      - "/mnemonic"
      - "--pyth-contract"
      - "0xC38B1dd611889Abc95d4E0a472A667c3671c08DE"
      - "--price-endpoint"
      - "https://xc-testnet.pyth.network"
      - "--price-config-file"
      - "/price_config"
    configs:
      - command_config
      - mnemonic
      - price_config
configs:
  command_config:
    file: ./nexon-config.testnet.json
  mnemonic:
    file: ./nexon-mnemonic.testnet.txt
  price_config:
    file: ./nexon-price-config.testnet.yaml
